[package]
name = "redhook_ex_readlinkspy"
version = "0.0.1"
authors = ["Geoffrey Thomas <geofft@ldpreload.com>"]

[lib]
name = "readlinkspy"
crate_type = ["dylib"]

[dependencies.redhook]
path = "../.."
